[book]
authors = ["Bitcoin-Wildlife-Sanctuary"]
language = "en"
multilingual = false
src = "src"
title = "Bitcoin Circle STARK"

[output.html]
git-repository-url = "https://github.com/Bitcoin-Wildlife-Sanctuary/bitcoin-circle-stark/"
edit-url-template = "https://github.com/Bitcoin-Wildlife-Sanctuary/bitcoin-circle-stark/book/{path}"

[output.html.playground]
runnable = false
